extends: substitution
level: warning
link: https://kubernetes.io/docs/contribute/style/style-guide/#use-upper-camel-case-for-api-objects
message: Use '%s' ao invés de '%s'.

ignorecase: false

action:
  name: replace
swap:
  cron job: CronJob

  "[Kk]ubernetes deployment": Kubernetes Deployment

  "d[ae][ae]mon[Ss]et": DaemonSet
  "replica[Ss]et": ReplicaSet
  "stateful[Ss]et": StatefulSet
  pod: Pod

  "[Kk]ubelet": '`kubelet`'
  "[Kk]ubectl": '`kubectl`'